In [ ]:
import pandas as pd 
import numpy as np

In [4]:
data = pd.read_csv('price forecast.csv')
data.head()

,Close price,Exchange Date,Timestamp (coc-mpyn-prfr),Last Quote Close (coc-mpyn-prfr),Timestamp (coc-mpys-prfr),Last Quote Close(coc-mpys-prfr),Timestamp(coc-mpyns-prfr),Last Quote Close(coc-mpyns-prfr),Timestamp (coc-mpyn-wdam),Last Quote Close(coc-mpyn-wdam),Timestamp(coc-mpys-wdam),Last Quote Close(coc-mpys-wdam),Timestamp(coc-mpyns-wdam),Last Quote Close(coc-mpyns-wdam)
0,561,4-Jan-00,1/4/2000,0.000000,1/1/2000,0.0,1/1/2000,0.0,1/4/2000,0.000000,1/1/2000,0.000000,1/1/2000,0.018868
1,560,5-Jan-00,1/5/2000,0.000000,1/2/2000,0.0,1/2/2000,0.0,1/5/2000,0.000000,1/2/2000,0.000000,1/2/2000,0.123457
2,556,6-Jan-00,1/6/2000,-0.004343,1/3/2000,0.0,1/3/2000,0.0,1/6/2000,0.004343,1/3/2000,0.333333,1/3/2000,0.014085
3,564,7-Jan-00,1/7/2000,0.002181,1/4/2000,0.0,1/4/2000,0.0,1/7/2000,0.000000,1/4/2000,0.000000,1/4/2000,0.000000
4,565,10-Jan-00,1/10/2000,-0.014851,1/5/2000,0.0,1/5/2000,0.0,1/10/2000,0.000000,1/5/2000,0.000000,1/5/2000,0.000000

In [7]:
data.tail()

,Close price,Exchange Date,Timestamp (coc-mpyn-prfr),Last Quote Close (coc-mpyn-prfr),Timestamp (coc-mpys-prfr),Last Quote Close(coc-mpys-prfr),Timestamp(coc-mpyns-prfr),Last Quote Close(coc-mpyns-prfr),Timestamp (coc-mpyn-wdam),Last Quote Close(coc-mpyn-wdam),Timestamp(coc-mpys-wdam),Last Quote Close(coc-mpys-wdam),Timestamp(coc-mpyns-wdam),Last Quote Close(coc-mpyns-wdam)
7211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/5/2019,0.009421
7212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/6/2019,0.086849
7213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/7/2019,0.009484
7214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/8/2019,0.015387
7215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/9/2019,0.010126

In [12]:
pd.datetime('data[Timestamp(coc-mpyn-prfr)]', format = '%d-%m-%y')

TypeError: an integer is required (got type str)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7216 entries, 0 to 7215
Data columns (total 14 columns):
Close price                         4957 non-null object
Exchange Date                       4957 non-null object
Timestamp (coc-mpyn-prfr)           7029 non-null object
Last Quote Close (coc-mpyn-prfr)    7029 non-null float64
Timestamp (coc-mpys-prfr)           6937 non-null object
Last Quote Close(coc-mpys-prfr)     6937 non-null float64
Timestamp(coc-mpyns-prfr)           7047 non-null object
Last Quote Close(coc-mpyns-prfr)    7047 non-null float64
Timestamp (coc-mpyn-wdam)           6939 non-null object
Last Quote Close(coc-mpyn-wdam)     6939 non-null float64
Timestamp(coc-mpys-wdam)            7190 non-null object
Last Quote Close(coc-mpys-wdam)     7190 non-null float64
Timestamp(coc-mpyns-wdam)           7216 non-null object
Last Quote Close(coc-mpyns-wdam)    7216 non-null float64
dtypes: float64(6), object(8)
memory usage: 789.3+ KB

In [15]:
#import matplotlib.pyplot as plt
#data.hist()

In [ ]:
#pd.options.display.mpl_style = 'default'
#data.boxplot()